trigger: none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: security-lib-ci # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

steps:
- bash: echo "app-ci runs after security-lib-ci completes"
- bash: mkdir $(System.DefaultWorkingDirectory)/build
- bash: echo "this is the build artifact" > output.txt
  workingDirectory: $(System.DefaultWorkingDirectory)/build
- publish: $(System.DefaultWorkingDirectory)/build
  artifact: my-artifact