trigger: none

resources:
  pipelines:
  - pipeline: first # Name of the pipeline resource.
    source: first-build # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

stages:
  - stage: my_stage
    jobs:
      - deployment: my_deployment
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: echo "app-ci runs after security-lib-ci completes"
                - bash: ls $(Pipeline.Workspace)
                - download: specific
                  pipeline: first
                - bash: ls $(Pipeline.Workspace)